services:
  mysql-db:
    image: mysql:8.0
    container_name: BlogAppMySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
    - "3308:3306"
    volumes:
    - ./mysql-data:/var/lib/mysql
    networks:
    - bloggapp-network
  bloggapp:
    build: .
    container_name: BlogApp_Container
    restart: always
    ports:
      - "8081:8080"
    depends_on:
       mysql-db:
          condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bloggappcontainer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    networks:
      - bloggapp-network
networks:
  bloggapp-network:
volumes:
  mysql-data: